### PR TITLE
feat: Add endpoint for fetching sponsors

### PR DESCRIPTION
**Pull request by michaelbukachi**
## What is the Purpose?
Add endpoint integration for fetching sponsors

## What was the approach?
Set up API service

## Are there any concerns to addressed further before or after merging this PR?
State some additional info if any. For instance running `install` or setting some environment variable(s)

## Mentions?
@wangerekaharun 

## Issue(s) affected?
#146

### CODE REVIEW

**Comment by wangerekaharun** [comment]
[Implement Fetch Sponsors](https://trello.com/c/muMuCYFr/128-implement-fetch-sponsors)

**Review by wangerekaharun — APPROVED** [review]
Everything looks fine.

I have a quick question, how will having a interface for each endpoint scale with the other endpoints in mind too @michaelbukachi

**Comment by michaelbukachi** [comment]
> Everything looks fine.
> 
> I have a quick question, how will having a interface for each endpoint scale with the other endpoints in mind too @michaelbukachi

We can add other interfaces and register them with Retrofit. I tried to group the even endpoints together.

**Comment by wangerekaharun** [comment]
> > Everything looks fine.
> > I have a quick question, how will having a interface for each endpoint scale with the other endpoints in mind too @michaelbukachi
> 
> We can add other interfaces and register them with Retrofit. I tried to group the even endpoints together.

So ideally an interface for each group, what are the downsides of having endpoints defined on one interface?

**Comment by michaelbukachi** [comment]
There really is no advantage/disadvantage. besides aesthetics. We could put all endpoints in one interface and just group them by comments.

**Comment by wangerekaharun** [comment]
> There really is no advantage/disadvantage. besides aesthetics. We could put all endpoints in one interface and just group them by comments.

Alright, got it, going ahead to merge this

**Pull request merged**
