### PR TITLE
Auto-hide bottom navigation view

### LINKED ISSUE #174: Auto-hide bottom navigation bar on scroll up and show on scroll up
This will prevent issues around handling bottom paddings for scrolling layouts and increases the real estate given we have two bars at the top and bottom

### PR DESCRIPTION
**Pull request by muth0mi**
## What is the Purpose?
This PR seems to auto hide the bottom navigation view when scrolling downwards and showing it while scrolling upwards to increase screen estate for the content and to avoid dirty paddings

## What was the approach?
1. Add a HideBottomViewOnScrollBehavior flag to the bottom nav bar
1. Remove paddings set in the other fragments

## Are there any concerns to addressed further before or after merging this PR?
No

## Mentions?
@wangerekaharun @michaelbukachi 

## Issue(s) affected?
closes #174

### CODE REVIEW

**Review by muth0mi — COMMENTED** [review]
_

**Review by michaelbukachi — APPROVED** [review]
Nicely done. @wangerekaharun we need a ticket to address the kotlin synthetics :laughing:

**Comment by muth0mi** [comment]
> Nicely done. @wangerekaharun we need a ticket to address the kotlin synthetics

We could go databinding all the way.

**Comment by michaelbukachi** [comment]
> > Nicely done. @wangerekaharun we need a ticket to address the kotlin synthetics
> 
> We could go databinding all the way.

Agreed :ok_hand:

**Comment by muth0mi** [comment]
> > > Nicely done. @wangerekaharun we need a ticket to address the kotlin synthetics
> > 
> > 
> > We could go databinding all the way.
> 
> Agreed

I've created an issue (#177 )

**Comment by wangerekaharun** [comment]
> Nicely done. @wangerekaharun we need a ticket to address the kotlin synthetics

I thought we started well  with `viewBinding`

**Review by wangerekaharun — APPROVED** [review]
Great work on this

**Comment by wangerekaharun** [comment]
[Auto hide btm nav](https://trello.com/c/dltxaSVN/158-auto-hide-btm-nav)

**Comment by wangerekaharun** [comment]
[Auto-hide bottom navigation bar on scroll up and show on scroll up](https://trello.com/c/K71YPiZp/155-auto-hide-bottom-navigation-bar-on-scroll-up-and-show-on-scroll-up)

**Pull request merged**
