### PR TITLE
Feat: Auth module view model setup

### PR DESCRIPTION
**Pull request by ghost**
## What is the Purpose?
Setup auth module view model

## What was the approach?
setup the view model. Data binding was employed

## Are there any concerns to addressed further before or after merging this PR?
Tests for the view model

## Mentions?
@michaelbukachi @wangerekaharun @JabezNzomo99 

## Issue(s) affected?
#44

### CODE REVIEW

**Review by wangerekaharun — CHANGES_REQUESTED** [review]
@chepsi  Kindly add tests and logic on the view model too.

**Comment by wangerekaharun** [comment]
[Setup AuthViewModel in auth module](https://trello.com/c/df7puUQ0/31-setup-authviewmodel-in-auth-module)

**Comment by michaelbukachi** [comment]
@chepsi any progress?

**Comment by chepsi** [comment]
Yes. I am finalizing on a few things. Like the lock/unlock icon on the menu item if you are logged in/out and the view that is inflated if you are logged in/not.

**Comment by wangerekaharun** [comment]
[Setup AboutViewModel in about module](https://trello.com/c/7ZFBF3LA/33-setup-aboutviewmodel-in-about-module)

**Pull request closed without merging**
