### PR TITLE
Dark theme

### PR DESCRIPTION
**Pull request by muth0mi**
## What is the Purpose?
Introduction of dark theme to the application and modifying the toolbar to resemble the mockup design

## What was the approach?
Dark mode functionality was effected by placing a toggle in the toolbar and modifying resource files and color & style values to allow for a custom dark mode.
The toolbar design was implemented by creating and showing appropriate fragments for the different pages and for different login states.

## Are there any concerns to addressed further before or after merging this PR?
No

## Mentions?
@wangerekaharun @michaelbukachi @chepsi @odaridavid

## Issue(s) affected?
Applies dark theme in #87
Styles toolbar in #59

### CODE REVIEW

**Comment by michaelbukachi** [comment]
Hi @muth0mi Thanks for your contribution!

**Comment by michaelbukachi** [comment]
However, we insist on maintaining the scope of the a PR/Issue for easier tracking and management. I noticed that you added countdown logic. Nice. However, this is considered "out of scope". Please remove any code that doesn't fall within the PR or issue specified.

**Comment by wangerekaharun** [comment]
@muth0mi thank you for your contribution. However, revert the changes that are refffered to as out of scope. All toolbar issues are currently being worked on #59

**Comment by muth0mi** [comment]
I worked on bits of the toolbar for to ensures the colours matched the designs both dark and light modes. Should I remove all the layout code affecting the toolbar or just the programatic code doing the countdown?

**Comment by wangerekaharun** [comment]
> I worked on bits of the toolbar for to ensures the colours matched the designs both dark and light modes. Should I remove all the layout code affecting the toolbar or just the programatic code doing the countdown and mention the PR to be affecting #59?

Yes you can remove the bits, am also running your code to see if i can borrow a leaf from your implementation. Alternatively, am working on branch issue  -59

**Comment by muth0mi** [comment]
I have removed the toolbar logic (countdown functionality) and retained the toolbar design since removing it will affect the colours and styles used. I suggest merging the codebase and then we can pick it up on issue #59

**Comment by wangerekaharun** [comment]
[Dark Theme](https://trello.com/c/8foCCzAR/72-dark-theme)

**Comment by wangerekaharun** [comment]
@muth0mi Can you kindly remove even the related files. The only change that we will accept is the adding icon on the toolbar that was previously there.

**Comment by muth0mi** [comment]
Alright. Give me a few minutes.

**Comment by wangerekaharun** [comment]
@muth0mi Hold on tight as we try and address all the issues before merging this PR.

Here's a couple of things to polish this to the next level :
- Some text and icons are still not changing their colors to reflect the dark theme colors as on the design an example is the Key Note Speaker text label which maintains black and should be white
- Check on the texts on home screen
- Icons on the feed fragment
- Share Bottom Sheet Fragment(Shows upon user clicking share icon on feed) 
- Share bottom sheet background on sessions
- Twitter Icon on the speaker details  screen
- Text color - the white is somehow dull

**Comment by muth0mi** [comment]
I didn't want to move forward with modifying the main content colours given there's work in progress in issue #89. Once that is closed I can move forward to apply proper colours in all the components.

**Comment by wangerekaharun** [comment]
Okay no problem. Going ahead to merge this.

**Pull request merged**
