### PR TITLE
Issue 61

### PR DESCRIPTION
**Pull request by wangerekaharun**
## What is the Purpose?
This PR Addresses the following issues
- App Navigation to all the required sections
        - From About Details to Team Member Navigation
        - From Session Details to Speaker Details
        - From Home Fragment to Speaker Details
        - From Home Fragment to Session Details
        - From Session Schedule to Sesssion Details
- Adding icons to bottom bar
- Minor code improvements

## What was the approach?
Using Safe Args Directions for Navigating to Different Fragments

## Are there any concerns to addressed further before or after merging this PR?
Now that most of the parts are already wired up. Time to create the different animations and transitions.

## Mentions?
@michaelbukachi @JabezNzomo99 @chepsi 

## Issue(s) affected?
#61 #64 #63

### CODE REVIEW

**Comment by wangerekaharun** [comment]
[Add Respective Bottom Bar Icons](https://trello.com/c/yEWADGK4/49-add-respective-bottom-bar-icons)

**Comment by wangerekaharun** [comment]
[Implement Team Member Details Navigation](https://trello.com/c/gYN17Cpc/50-implement-team-member-details-navigation)

**Comment by wangerekaharun** [comment]
[Implement Navigation to Session Details](https://trello.com/c/dS00fcFR/46-implement-navigation-to-session-details)

**Comment by wangerekaharun** [comment]
[Setup state in SplashScreenActivity](https://trello.com/c/wFYVEge3/42-setup-state-in-splashscreenactivity)

**Review by michaelbukachi — APPROVED** [review]

**Pull request merged**
