### PR TITLE
Coding convention

### PR DESCRIPTION
**Pull request by PhilomenaMbura**
## What is the Purpose?
Updating Coding conventions to be used.

## What was the approach?
Look at the Coding convenction section

## Are there any concerns to addressed further before or after merging this PR?
No concerns

## Mentions?
@chepsi @michaelbukachi 

## Issue(s) affected?
#4

### CODE REVIEW

**Comment by michaelbukachi** [comment]
@chepsi did you gitignore the `build` dir under `buildSrc`?

**Comment by michaelbukachi** [comment]
@wangerekaharun it seems only the root `build` dir is ignored.

**Comment by wangerekaharun** [comment]
> @wangerekaharun it seems only the root `build` dir is ignored.

Yes seen the buildSrc/build directory on the branch. 

@PhilomenaMbura  can you add this directory to .gitignore

**Comment by michaelbukachi** [comment]
> > @wangerekaharun it seems only the root `build` dir is ignored.
> 
> Yes seen the buildSrc/build directory on the branch.
> 
> @PhilomenaMbura can you add this directory to .gitignore

If she's using linux, she can run `git rm --cached -rf buildSrc/build` as well to remove the added files.

**Comment by michaelbukachi** [comment]
@PhilomenaMbura The entry in `.gitignore` has to be `/buildSrc/build` not `/buildSrc` since there are files in `buildSrc` that are still needed.

**Comment by wangerekaharun** [comment]
[Coding convention](https://trello.com/c/61kK6KJp/19-coding-convention)

**Pull request merged**
