### PR TITLE
Issue 110 Setting up collapsing toolbars

### PR DESCRIPTION
**Pull request by ben-mathu**
What is the Purpose?
Setting up the collapsing toolbar for session, speaker and organizer details screens

What was the approach?
As per design requirements

Are there any concerns to addressed further before or after merging this PR?
For the organizer details screen the organizer's avatar is hidden under the status bar.

Mentions?
@wangerekaharun @michaelbukachi 

Issue(s) affected?
#110

### CODE REVIEW

**Comment by ben-mathu** [comment]
@michaelbukachi Why did travis ci fail with ClassNotFoundException JAXBException?

**Comment by michaelbukachi** [comment]
> @michaelbukachi Why did travis ci fail with ClassNotFoundException JAXBException?

I'm more curious as to why travis run. We had removed it. Maybe you re-introduced the `travis-ci.yml` file during the merge.

**Comment by ben-mathu** [comment]
Ooh okay, i changed from the parent repository to the forked repository in my account and made sure i merged any commits to branch develop. Should i remove the `travis_ci.yml` file? is there any more configuration needed?

**Comment by michaelbukachi** [comment]
Yeah. Removing it should resolve the issue.

**Comment by michaelbukachi** [comment]
@wangerekaharun can you check this?

**Comment by ben-mathu** [comment]
They are all set up maybe its an issue with the screen size i was using 720x1280 screen on the emulator and actual device. What screen size were you testing this on?

**Comment by wangerekaharun** [comment]
> They are all set up maybe its an issue with the screen size i was using 720x1280 screen on the emulator and actual device. What screen size were you testing this on?

Screenshot_2020-05-04-22-26-40-570_com android254 droidconKE2020
Screenshot_2020-05-04-22-27-25-141_com android254 droidconKE2020

My screen size is 6.39", but the toolbar is not there since the layouts are the same.

**Comment by ben-mathu** [comment]
@wangerekaharun sorry i meant the screen dimensions, but its okay.

**Comment by ben-mathu** [comment]
@wangerekaharun so you are testing this changes based on the droidcon's repo's develop branch, but the develop branch i am working on is on my repository these changes have no yet been updated to develop.

**Comment by wangerekaharun** [comment]
> @wangerekaharun so you are testing this changes based on the droidcon's repo's develop branch, but the develop branch i am working on is on my repository these changes have no yet been updated to develop.

I have your origin too, so i fetched your latest changes and switched to develop. Session Details is working fine. But will retest again

**Comment by ben-mathu** [comment]
Okay i can't think of where the problem is, i have tested on screens with more pixels, ie 1028x1440 and it works fine. @michaelbukachi are you having this problem?

**Comment by michaelbukachi** [comment]
Hmm. The toolbar "disappears" when you scroll instead of collapsing. @wangerekaharun is this what you mean?

**Comment by wangerekaharun** [comment]
> Hmm. The toolbar "disappears" when you scroll instead of collapsing. @wangerekaharun is this what you mean?

Nope. On Speaker Details and Organizer Details didn't see the toolbar. Am testing this again on my end to see if i missed something.

**Comment by wangerekaharun** [comment]
[Setup Collapsing Toolbars](https://trello.com/c/ym7QYU4c/95-setup-collapsing-toolbars)

**Comment by ben-mathu** [comment]
Okay

**Comment by ben-mathu** [comment]
is that how you expected it to be, or was the toolbar to remain as the user scrolls the screen?

**Comment by wangerekaharun** [comment]
> is that how you expected it to be, or was the toolbar to remain as the user scrolls the screen?

Either way would work for me, since on the design there was no indication of how it was supposed to be

**Pull request merged**
