### PR TITLE
Setup Lint Plugins

### PR DESCRIPTION
**Pull request by wangerekaharun**
## What is the Purpose?
Setting up Lint Plugins.

## What was the approach?
First thing, was to use the new way of declaring Gradle Plugins which was introduced in `Version 5.6`. This eliminates the old way of defining the buildscript where all plugins are fetched from the Gradle Plugin Portal. For those plugins that cannot be found here,there is a resolution strategy to define how they will be fetched. Setup for the `plugins{}` can be found here  in [build.gradle.kts](https://github.com/droidconKE/droidconKE2020App/blob/issue-117/build.gradle.kts) and the plugin management is here [settings.gradle.kts](https://github.com/droidconKE/droidconKE2020App/blob/issue-117/settings.gradle.kts) 

The rules for the `detekt` can be found in this [configuration file](https://github.com/droidconKE/droidconKE2020App/blob/issue-117/detekt.yml) and the `ktLint` file is [here](https://github.com/droidconKE/droidconKE2020App/blob/issue-117/.editorconfig).

Before every PR make sure you run the following commands:
1 `./gradlew ktlintFormat`
2 `./gradlew ktlintCheck`
3 `./gradlew detekt`

In case any of them fails, be sure to address the errors cause the same will be integrated on CI so no PR will be merged without this being successful.

@michaelbukachi over to you after this is merged to setup CI on the same.

## Are there any concerns to addressed further before or after merging this PR?
A couple of them : 

- File changes are more since i had to format the whole project according to the rules on `ktLint` and `detekt`.
- @muth0mi @michaelbukachi @ben-mathu @chepsi @JabezNzomo99 @PhilomenaMbura @Anniekobia Cross check on the file changes to see if there's any unitended change on the PR.

## Mentions?
- @muth0mi @michaelbukachi @ben-mathu @chepsi @JabezNzomo99

## Issue(s) affected?
#117

### CODE REVIEW

**Comment by wangerekaharun** [comment]
[Setup Lint Plugins](https://trello.com/c/kIxKnxeQ/102-setup-lint-plugins)

**Comment by michaelbukachi** [comment]
@wangerekaharun You've added build files to the commit. :sweat_smile:

**Comment by michaelbukachi** [comment]
Let's also add github actions for linting.

**Comment by wangerekaharun** [comment]
> @wangerekaharun You've added build files to the commit.

Seen this, let me fix that and revert.

**Comment by wangerekaharun** [comment]
> @wangerekaharun You've added build files to the commit.

Fixed this let me close this

**Pull request closed without merging**
