### PR TITLE
Added Custom Switch

### PR DESCRIPTION
**Pull request by wangerekaharun**
## What is the Purpose?
Adding custom switch 

## What was the approach?
Added `thumb` attribute to switch with a star drawable

## Are there any concerns to addressed further before or after merging this PR?
No Concerns

## Mentions?
@michaelbukachi @JabezNzomo99 

## Issue(s) affected?
#62

### CODE REVIEW

**Comment by wangerekaharun** [comment]
[Implement custom switch For sessions filter](https://trello.com/c/qyajQPar/47-implement-custom-switch-for-sessions-filter)

**Comment by michaelbukachi** [comment]
@wangerekaharun i'm getting  a databinding error. Is this PR based off `develop` or the code from the other PR?

**Comment by wangerekaharun** [comment]
Forgot to base it off develop first, that might be the reason for the error

**Comment by michaelbukachi** [comment]
> Forgot to base it off develop first, that might be the reason for the error

When you do let me know, so that I can test it locally.

**Comment by wangerekaharun** [comment]
Closing this for now, will create another PR addressing this

**Pull request closed without merging**
