### PR TITLE
Add  a splash screen animation (Issue 53)

### PR DESCRIPTION
**Pull request by jama5262**
## What is the Purpose?
Adds an animated splash screen

## What was the approach?
Created a `SplashScreenActivity` and animates  using [AndroidAnimation](https://github.com/jama5262/AndroidAnimation) library and later opens the `HomeActivity` screen after the animation ends

## Are there any concerns to addressed further before or after merging this PR?
1. Did not create a feature for the splash screen, because the bottom nav was always there in the home screen, hence create an activity `SplashScreenActivity` in the app module

## Mentions?
@wangerekaharun @chepsi @michaelbukachi

## Issue(s) affected?
#53

### CODE REVIEW

**Comment by michaelbukachi** [comment]
Hello @jama5262. Thanks for the PR. Your animation library is spot on!  One thing we have to consider is that we don't want the animation to show every time. Imagine a situation where you are late for the conference. You just arrived. You really need to see active sessions so that you can hope into one of them. An animation wouldn't be a good idea in this scenario since you'd want the app to load as fast as possible. We will open another issue to handle this extra piece of logic.
I'll merge this as soon as any of the others check this out.
@chepsi @wangerekaharun @JabezNzomo99 check this out!

**Comment by jama5262** [comment]
@michaelbukachi Thanks. I was also on the fence on actually adding the splash screen in terms of branding the app, but we could add a shared preference to show the splash screen for the first time opening the app.

**Comment by michaelbukachi** [comment]
@jama5262 I've created #57 for the extra functionality. I'll merge this now.

**Comment by michaelbukachi** [comment]
@jama5262 Instead of using an image you can make the animation play faster. Just a thought.

**Comment by wangerekaharun** [comment]
Yes making animation play faster will also be good.

**Comment by wangerekaharun** [comment]
[Add  a splash screen animation](https://trello.com/c/JpJr3klf/40-add-a-splash-screen-animation)

**Pull request merged**
