### PR TITLE
Setup AboutViewModel

### PR DESCRIPTION
**Pull request by ben-mathu**
## What is the Purpose?
Setting up viewmodel for about module 

## What was the approach?
Setting up view model according guided descriptions.

## Are there any concerns to addressed further before or after merging this PR?
There are no tests for viewmodel.

## Mentions?
@michaelbukachi @wangerekaharun @chepsi @JabezNzomo99 

## Issue(s) affected?
#47

### CODE REVIEW

**Comment by ben-mathu** [comment]
closing this to add test for view model.

**Comment by ben-mathu** [comment]
Update the about feature by setting up view model and creating unit and instrumented tests.

**Comment by wangerekaharun** [comment]
[Setup AboutViewModel in about module](https://trello.com/c/7ZFBF3LA/33-setup-aboutviewmodel-in-about-module)

**Comment by michaelbukachi** [comment]
Hey. @ben-mathu nice work. Next time please open a new PR. The current PR description doesn't match the code.

**Comment by ben-mathu** [comment]
Okay, but I edited the PR description, probably did not take effect. Should edit it, @michaelbukachi ?

**Pull request merged**
