### PR TITLE
feat: Add design for feeds view

### PR DESCRIPTION
**Pull request by michaelbukachi**
## What is the Purpose?
Implement design for feeds page

## What was the approach?
Implement layout files and dummy data for display

## Are there any concerns to addressed further before or after merging this PR?
The current night theme colours don't match the design. This can be addressed later since the logic will affect the entire app.

## Mentions?
@chepsi 
@wangerekaharun 

## Issue(s) affected?
#31

### CODE REVIEW

**Comment by michaelbukachi** [comment]
[Feed  module design](https://trello.com/c/j37FmdHh/14-feed-module-design)

**Comment by michaelbukachi** [comment]
> Everything looks fine. Couldn't find any issues with the implementation.
> 
> Here are some comments which are not critical though.
> 
>     * Am a fan of passing a function as a listener on the adapter and using a lambda on the activity/fragment part
> 
>     * On bindFeed, we can use scoping functions to make it more better

Oh! I totally forgot about about lambda functions. Let me make that change. Do you mind elaborating on scoping functions?

**Comment by michaelbukachi** [comment]
Nevermind. Got it.

**Comment by wangerekaharun** [comment]
> > Everything looks fine. Couldn't find any issues with the implementation.
> > Here are some comments which are not critical though.
> > ```
> > * Am a fan of passing a function as a listener on the adapter and using a lambda on the activity/fragment part
> > 
> > * On bindFeed, we can use scoping functions to make it more better
> > ```
> 
> Oh! I totally forgot about about lambda functions. Let me make that change. Do you mind elaborating on scoping functions?

We can have something like 

`     fun bindFeed(feed: Feed)  {
            with(feed){
                tvcontent.text = content
                feedImage.load(imageUrl) {
                    transformations(RoundedCornersTransformation(12f))
                }
                tvTime.text = time
                shareButton.setOnClickListener {
                    listener.onShareClicked(feed)
                }

            }
        }`

This is a nice to have feature.
Also can we use view binding on the adapter too? 

One last thing is name the views different from the ones from data class.

**Comment by michaelbukachi** [comment]
> > > Everything looks fine. Couldn't find any issues with the implementation.
> > > Here are some comments which are not critical though.
> > > ```
> > > * Am a fan of passing a function as a listener on the adapter and using a lambda on the activity/fragment part
> > > 
> > > * On bindFeed, we can use scoping functions to make it more better
> > > ```
> > 
> > 
> > Oh! I totally forgot about about lambda functions. Let me make that change. Do you mind elaborating on scoping functions?
> 
> We can have something like
> 
> ` fun bindFeed(feed: Feed) {
> with(feed){
> tvcontent.text = content
> feedImage.load(imageUrl) {
> transformations(RoundedCornersTransformation(12f))
> }
> tvTime.text = time
> shareButton.setOnClickListener {
> listener.onShareClicked(feed)
> }
> 
> ```
>         }
>     }`
> ```
> 
> This is a nice to have feature.
> Also can we use view binding on the adapter too?
> 
> One last thing is name the views different from the ones from data class.

We can't use viewbinding in the adapter since we'd need to pass a variable to the xml. We'd have to got with databinding instead.

**Comment by wangerekaharun** [comment]
> We can't use viewbinding in the adapter since we'd need to pass a variable to the xml. We'd have to got with databinding instead.

Noted.

**Pull request merged**
