### PR TITLE
Material theming

### PR DESCRIPTION
**Pull request by EdwardMuturi**
## What is the Purpose?
Use global theming for easy style management and re-usability. 

## What was the approach?
Use android styles naming convention i.e `StyleType.GroupName.SubGroupName.Variance`

## Are there any concerns to addressed further before or after merging this PR?
Just applied naming before proceeding. If this is okay,  I can continue with the changes.

## Mentions?
Mention persons you'd like to review this PR

## Issue(s) affected?
#89

### CODE REVIEW

**Comment by odaridavid** [comment]
Looks good to me ,you can merge this after #95 gets merged

**Comment by muth0mi** [comment]
Looks good to me as well

**Comment by wangerekaharun** [comment]
@EdwardMuturi There are some conflicts, resolve them the we can go ahead to merge this.

**Comment by EdwardMuturi** [comment]
okay.

**Pull request merged**
