### PR TITLE
Issue 59

### PR DESCRIPTION
**Pull request by wangerekaharun**
## What is the Purpose?
Adding dynamic toolbar for Home,Feed ,Feeback Fragment
## What was the approach?
Recommended by @michaelbukachi, the approach was to use toolbar as a custom view and change the layouts on the custom view.

## Are there any concerns to addressed further before or after merging this PR?
Created a separate issue on #110  to address the fragments that require collapsing toolbars
## Mentions?
@michaelbukachi @chepsi @muth0mi 

## Issue(s) affected?
#59

### CODE REVIEW

**Comment by wangerekaharun** [comment]
[Dynamic Toolbar Design](https://trello.com/c/VCR3rBrG/44-dynamic-toolbar-design)

**Comment by wangerekaharun** [comment]
Yes am addressing them together with the resources issue

**Review by michaelbukachi — APPROVED** [review]
Nice.

**Comment by wangerekaharun** [comment]
> Can we merge #112 first so that we can make use of the bundle checks?

In support, actually i am running command right now to check, remembered right after creating the PR.

> Nice.

Confirmed. The checks are working fine. Let me work on Lint Rules

**Review by muth0mi — COMMENTED** [review]
Oops. No prob though. Everything works just fine. 
I never anticipated that method of implementing the toolbar but I'm happy the way it turned out :-D.

One thing I noticed is a few inconsistencies in the toolbar icons sizes and constraints. Very minor but noticable when you jump between screens. I think it can be fixed by extracting the dimensions into dimen resources and reusing them across the layouts and widgets. That can be done later in UI fine-tuning. :+1: :+1:

**Pull request merged**
