### PR TITLE
Feature sessions ui implementation - # Issue 34

### PR DESCRIPTION
**Pull request by JabezNzomo99**
## What is the Purpose?
Sessions Module UI implementation - #34 

## What was the approach?
I followed the design doc and where neccessary i referred to standard material design guidelines

## Are there any concerns to addressed further before or after merging this PR?
1. I have not setup navigation within session feature, i encountered an issue when clicking a session item to navigate to the session details fragment, this can be looked into as a task.
2. I have not setup motion layout for some of the views 
3. Session items on the Sessions Fragment are supposed to have a custom item decorator, i am working on this and will address it in the subsequent PR. 
4. I implemented filter feature on sessions using a bottom sheet fragment as opposed to what was in the design, review it on the app and let me know what you think. My reason for doing this was to allow quick user action and smooth transition when filtering.

## Mentions?
@wangerekaharun 
@Anniekobia 
@PhilomenaMbura 
@michaelbukachi 
@chepsi 

## Issue(s) affected?
#34

### CODE REVIEW

**Comment by michaelbukachi** [comment]
Nicely done. Just a couple of issues to address later.
Here, the constraints are a bit off.
screenshot_20200316233746

Is this supposed to be this way?
screenshot_20200316233828

I'll merge the changes now to close the design phase.

**Comment by JabezNzomo99** [comment]
@michaelbukachi  Thank you for pointing out the constraints UI issue, let me review it and make the neccessary changes.

On the filter screen, i thought it would have been easier for the user to filter using a bottom sheet, or what do you think? Should i follow the original implementation?

**Comment by michaelbukachi** [comment]
Bottom sheet is fine. It's more android like. I was talking about the lack of a background.

**Comment by JabezNzomo99** [comment]
@michaelbukachi I have made some changes on the constraints
Screenshot_1584393841

**Comment by michaelbukachi** [comment]
Nice. Let's wait for @chepsi since harun isn't available this week.

**Comment by JabezNzomo99** [comment]
@michaelbukachi I'm here laughing at myself for not testing the layout with smaller screens. Also, on the bottom sheet filter, i'm trying to add a background color but it's not working as expected when i switch between themes

**Comment by michaelbukachi** [comment]
Haha. I'll always forget also. I'll check out the theme issue on my end during the day.

**Comment by JabezNzomo99** [comment]
> Haha. I'll always forget also. I'll check out the theme issue on my end during the day.

@michaelbukachi Also check on navigation within a feature, when you click a session item to navogated to session detail, i kept on getting 'unknown fragment destination' error

**Comment by wangerekaharun** [comment]
Try and use Fragment Directions to avoid the unknown destination error. Am not able to do a full review at the moment, this should not be a blocker for tbe changes being merged. @michaelbukachi if everything is fine go ahead with the merge.

**Comment by michaelbukachi** [comment]
@wangerekaharun I can't merge because I'm not one of the reviewers for the PR

**Comment by wangerekaharun** [comment]
> @wangerekaharun I can't merge because I'm not one of the reviewers for the PR

Let me merge this, on mobile though-:)

**Review by wangerekaharun — APPROVED** [review]
Approving this, will also ho through the implementation later on, incase of anything will let you know

**Comment by wangerekaharun** [comment]
[Auth Module Design](https://trello.com/c/NTGkfSTt/13-auth-module-design)

**Pull request merged**
