### PR TITLE
Dynamically load sponsors

### PR DESCRIPTION
**Pull request by muth0mi**
## What is the Purpose?
This PR addresses issue #98 by allowing sponsors to be loaded dynamically

## What was the approach?
The issue was resolved by replacing the static images with 2 recycler views. One for gold sponsors that will have larger images and another one for other sponsors.

## Are there any concerns to addressed further before or after merging this PR?
Clean up unused resources after ensuring the initial image assets are not to be used in the app anymore

## Mentions?
@michaelbukachi @wangerekaharun 

## Issue(s) affected?
This PR closes issue #98

### CODE REVIEW

**Comment by muth0mi** [comment]
I'll do that later and push the changes

**Comment by wangerekaharun** [comment]
[Dynamically Load Sponsors In HomeFragment](https://trello.com/c/pAbOlLs8/83-dynamically-load-sponsors-in-homefragment)

**Comment by wangerekaharun** [comment]
[Dynamically Load Sponsors In HomeFragment](https://trello.com/c/pAbOlLs8/83-dynamically-load-sponsors-in-homefragment)

**Comment by wangerekaharun** [comment]
[Dynamically Load Sponsors In HomeFragment](https://trello.com/c/pAbOlLs8/83-dynamically-load-sponsors-in-homefragment)

**Pull request merged**
