### PR TITLE
Speaker Module Design Implementation

### PR DESCRIPTION
**Pull request by wangerekaharun**
## What is the Purpose?
Implementing the Design For The Speaker Module
## What was the approach?
As per the Design Guidlines.

## Are there any concerns to addressed further before or after merging this PR?
First time implementing ConstraintLayout, cause i felt we will require lots of Constraints :] . This means
- Design might not be at its best, help is required to polish it up to the next level.
- Paddings are a bit off.

However, will continue improving it gradually. Help will also be appreciated :-)

## Mentions?
@michaelbukachi @JabezNzomo99 @chepsi 

## Issue(s) affected?
#35

### CODE REVIEW

**Comment by wangerekaharun** [comment]
[Speaker Module Design](https://trello.com/c/hqfurc8e/18-speaker-module-design)

**Comment by wangerekaharun** [comment]
Before Merging we can polish up bit

**Comment by michaelbukachi** [comment]
Alright. Let me make some changes.

**Comment by michaelbukachi** [comment]
@wangerekaharun  checkout the changes I've made. I haven't managed to add a radius to the background overlay of the speaker image. It's not working with what I've tried.

**Comment by michaelbukachi** [comment]
Also. It seems like the bottom navigation is covering part of the screen. I've added a scrollview, but part of the content is still being covered.
screenshot_20200305031843

**Comment by wangerekaharun** [comment]
> @wangerekaharun checkout the changes I've made. I haven't managed to add a radius to the background overlay of the speaker image. It's not working with what I've tried.

Let me check the changes right away. Coil does have a way of adding that , not sure though, another option would be to wrap the speaker image inside a relative layout with a circular background

**Comment by wangerekaharun** [comment]
> Also. It seems like the bottom navigation is covering part of the screen. I've added a scrollview, but part of the content is still being covered.
> screenshot_20200305031843

Adding `android:layout_marginBottom="?attr/actionBarSize"` always does the trick for me to make layout not be hidden by the bottom navigation bar

**Comment by michaelbukachi** [comment]
> > @wangerekaharun checkout the changes I've made. I haven't managed to add a radius to the background overlay of the speaker image. It's not working with what I've tried.
> 
> Let me check the changes right away. Coil does have a way of adding that , not sure though, another option would be to wrap the speaker image inside a relative layout with a circular background

I used coil in the feeds page for something like that. Should probably work

**Comment by michaelbukachi** [comment]
Cool. The radius is not a blocker for now I think we can merge. We can have a discussion in the group on how to best use constraint layout with minimum effort. Maybe someone else if facing challenges.

**Pull request merged**
