### PR TITLE
Issue 105 speakers module

### PR DESCRIPTION
**Pull request by muth0mi**
## What is the Purpose?
This PR is in regard to issue #105. 

## What was the approach?
The issue was resolved by creating refactoring the speaker module and introducing a new fragment for speakers that is launching it upon clickingthe  ViewAll (Speakers) button.

## Are there any concerns to addressed further before or after merging this PR?
During development a new library [`javafaker` ](https://github.com/DiUS/java-faker) was introduced to generate diversified data. This should be removed afte implementing actual data sources

## Mentions?
@wangerekaharun @michaelbukachi 

## Issue(s) affected?
#105 #115

### CODE REVIEW

**Comment by muth0mi** [comment]
@wangerekaharun I have checked out from develop and cherry-picked specific commits from [issue-105](https://github.com/muth0mi/droidconKE2020App/tree/issue-105). The commits should be much cleaner now for your review.

**Comment by wangerekaharun** [comment]
[Toggle Speakers List Layout Manager on Clicking View All / Less ](https://trello.com/c/g5AUe4J9/90-toggle-speakers-list-layout-manager-on-clicking-view-all-less)

**Comment by muth0mi** [comment]
I felt listing the sessions on the speaker fragment would allow the user to easily view and navigate to the sessions they will be hosting instead of going all the way back to the home fragment and switching to the sessions fragment then filtering the sessions to find sessions for a specific speaker. 
It wasn't in the design but I thought it would be a welcome addition.

**Comment by muth0mi** [comment]
For landscape mode. Constraint layout doesn't change (reposition elements) to ease the user's interaction with them. Ie, in the speakers fragment, the screen height is now smaller and it makes no sense to lower the search bar as much to be reachable. Also, there's no point in having wide list cards given they are not very busy and having users scroll all the way on the shorter screen height, it makes more sense to have narrower cards and have the user scroll less to get to the bottom.

**Comment by wangerekaharun** [comment]
> For landscape mode. Constraint layout doesn't change (reposition elements) to ease the user's interaction with them. Ie, in the speakers fragment, the screen height is now smaller and it makes no sense to lower the search bar as much to be reachable. Also, there's no point in having wide list cards given they are not very busy and having users scroll all the way on the shorter screen height, it makes more sense to have narrower cards and have the user scroll less to get to the bottom.

Makes sense now

**Comment by wangerekaharun** [comment]
> I felt listing the sessions on the speaker fragment would allow the user to easily view and navigate to the sessions they will be hosting instead of going all the way back to the home fragment and switching to the sessions fragment then filtering the sessions to find sessions for a specific speaker.
> It wasn't in the design but I thought it would be a welcome addition.
> 
> I'm reverting to the documented design though.

We try as much as possible to follow the design unless in areas where it hard to implement a certain future.

**Comment by muth0mi** [comment]
I moved the model and the FakeRepoClass class to the repository module to share the Speaker object and the FakeSpeakerRepository between the home module and the speakers module without repeating the two in the both modules and without having the home home module depend on the speakers module (as in the initial implementation) which would also mean the sessions module depend on the same since it uses the SpeakerDetails fragment

**Comment by michaelbukachi** [comment]
@muth0mi That's beyond the scope of this PR. Ideally, this what the PR should cover:
-  Add speakers listing view in speakers module
- Add navigation from home to the view
That's it. It's alright to duplicate models, resources at the this point of the project. Any task that involves refactoring or correction can be put in a separate issue.

**Comment by muth0mi** [comment]
Alright. :+1: :+1:

**Pull request merged**
