### PR TITLE
Added SpeakerViewModel

### PR DESCRIPTION
**Pull request by wangerekaharun**
## What is the Purpose?
Adding SpeakerDetailsViewModel for Speaker Module
## What was the approach?
Adding SpeakerDetailsViewModel for Speaker Module

## Are there any concerns to addressed further before or after merging this PR?
Here are a few concerns to note
- I have not used databinding
- I have not written tests for the viewmodel

For the concerns, how do we go forward since at time not all contributors are comfortable with tests and databinding. How do we ensure consistency across the whole project

## Mentions?
@michaelbukachi @JabezNzomo99 @chepsi 
## Issue(s) affected?
#49

### CODE REVIEW

**Comment by wangerekaharun** [comment]
[Setup SpeakerViewModel in speaker module](https://trello.com/c/zsb74Uaz/27-setup-speakerviewmodel-in-speaker-module)

**Comment by michaelbukachi** [comment]
@wangerekaharun If a dev is not comfortable with `databinding` and `tests` we have to create follow up tasks to add those. Those tasks will only be done by them so that they learn. Also, they won't be allowed to take any additional tasks until they've completed those two extra tasks. Devs familiar with testing and databinding should help those who aren't.

**Comment by wangerekaharun** [comment]
@michaelbukachi  Seems there is no escaping this time :-). Alright let me know how to proceed with the tests on this one. Will add them right away

**Comment by michaelbukachi** [comment]
We are all on quarantine, there's no excuse like "there's no time" :laughing:

**Comment by wangerekaharun** [comment]
Okay , you can comment with the tasks for the tests so that i can work on them

**Comment by michaelbukachi** [comment]
Can we categorize it as a subtask for this issue so that we don't end up creating too many issues?

**Comment by wangerekaharun** [comment]
@michaelbukachi completed the data binding part, only tests remaining.

**Comment by wangerekaharun** [comment]
> Can we categorize it as a subtask for this issue so that we don't end up creating too many issues?

Yes we can, a checklist on Trello will work

**Comment by ben-mathu** [comment]
> @michaelbukachi completed the data binding part, only tests remaining.

Should we implement the bindingadapter class in the core module? It might have reusable code.

**Comment by michaelbukachi** [comment]
> > @michaelbukachi completed the data binding part, only tests remaining.
> 
> Should we implement the bindingadapter class in the core module? It might have reusable code.

Yeah. If the code has potential for reuse. Let's just put in `core` module.

**Comment by wangerekaharun** [comment]
> > @michaelbukachi completed the data binding part, only tests remaining.
> 
> Should we implement the bindingadapter class in the core module? It might have reusable code.

Let me do the refactor

**Comment by wangerekaharun** [comment]
Moved the BindingAdapter to core. However, this means we also add the coil, and ShapedImageView dependencies to core and also enable databinding. Am not sure if this is the correct approach.

Also i feel the tests tasks will be a blocker here for me, so  i would recommend we create a separate task and someone who is more comfortable with tests taking it. I don't want to write tests just for the sake of completing a task. 

So we can go ahead and merge this.

**Comment by michaelbukachi** [comment]
@wangerekaharun this is the only PR we should allow. Future tasks must have tests otherwise technical debt will be huge. Also, a still insist the a separate task must be assigned to the same person especially if it's a test task.

**Pull request merged**
