### PR TITLE
Show Sponsors on Home Fragment

### PR DESCRIPTION
**Pull request by wangerekaharun**
## What is the Purpose?
Show Sponsors on Home Fragment

## Are there any concerns to addressed further before or after merging this PR?
None

## Mentions?
@michaelbukachi 

## Issue(s) affected?
#154

### CODE REVIEW

**Comment by wangerekaharun** [comment]
[Fetch sponsors on HomeFragment](https://trello.com/c/2xnW9HQ8/135-fetch-sponsors-on-homefragment)

**Comment by wangerekaharun** [comment]
[Fetch sponsors on HomeFragment](https://trello.com/c/2xnW9HQ8/135-fetch-sponsors-on-homefragment)

**Comment by wangerekaharun** [comment]
[Fetch sponsors on HomeFragment](https://trello.com/c/2xnW9HQ8/135-fetch-sponsors-on-homefragment)

**Comment by wangerekaharun** [comment]
[Fetch sponsors on HomeFragment](https://trello.com/c/2xnW9HQ8/135-fetch-sponsors-on-homefragment)

**Review by michaelbukachi — APPROVED** [review]

**Pull request merged**
